version: '3.8'

services:
  web:
    image: drupal:10.0
    ports:
      - "8080:80"
    volumes:
      #- ./drupal:/var/www/html
      - ./web/modules/custom:/var/www/html/web/modules/custom
      - ./web/modules/custom/events_management:/var/www/html/web/modules/custom/events_management
      - ./web/themes/custom:/var/www/html/web/themes/custom
      - ./web/sites/default/files:/var/www/html/web/sites/default/files
    depends_on:
      - db
    build:
        context: ./
        dockerfile: ./Dockerfile

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "8082:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  db_data:
